#!/bin/bash

curdir=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

: ${MAKE:=make}
: ${MAKE_PARSER:=awk -f ${curdir}/make2json.awk}

{
cat <<EOF
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <style>
            $(cat ${curdir}/dag.css)
        </style>
        <script>
            $(curl -s https://d3js.org/d3.v3.min.js)
        </script>
    </head>
    <body id="body">
        <script>
            var makedbs = $(${MAKE} --debug=jobs -npk "$@" | ${MAKE_PARSER})
            $(cat ${curdir}/makegraph.js)
        </script>
    </body>
</html>
EOF
}
