#!/bin/bash

curdir=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

: ${MAKE:=make --debug=jobs -npk}
: ${MAKE_PARSER:=awk -f ${curdir}/make2json.awk}
: ${CSS:=cat ${curdir}/dag.css}
: ${D3JS:=curl -sS https://d3js.org/d3.v3.min.js}
: ${LAYOUT:=cat ${curdir}/makegraph.js}

cat <<EOF
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <style>
            $($CSS)
        </style>
        <script>
            $($D3JS)
        </script>
    </head>
    <body>
        <script>
            var makedbs = $($MAKE "$@" | $MAKE_PARSER)
            $($LAYOUT)
        </script>
    </body>
</html>
EOF
